//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostMySQLConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceStatus
    {
        public AttendanceStatus()
        {
            this.AttendanceSubmissionStatuses = new HashSet<AttendanceSubmissionStatus>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public bool Blocking { get; set; }
    
        public virtual ICollection<AttendanceSubmissionStatus> AttendanceSubmissionStatuses { get; set; }
    }
}
