//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostMySQLConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceSubmissionStatus
    {
        public int id { get; set; }
        public int SectionId { get; set; }
        public System.DateTime Day { get; set; }
        public int StatusId { get; set; }
        public int UpdateCount { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual AttendanceStatus AttendanceStatus { get; set; }
        public virtual Section Section { get; set; }
    }
}
