//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostMySQLConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeTableEntry
    {
        public GradeTableEntry()
        {
            this.AttendanceMarkings = new HashSet<AttendanceMarking>();
            this.CommentsGradedEffort = new HashSet<StudentComment>();
            this.CommentsGradedExam = new HashSet<StudentComment>();
            this.CommentsGradedFinal = new HashSet<StudentComment>();
            this.CommentsGradedTerm = new HashSet<StudentComment>();
            this.APRequests = new HashSet<APRequest>();
            this.TypedCredits = new HashSet<Credit>();
            this.ValuedCredits = new HashSet<Credit>();
        }
    
        public int id { get; set; }
        public int GradeTableID { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
    
        private ICollection<AttendanceMarking> AttendanceMarkings { get; set; }
        public virtual GradeTable GradeTable { get; set; }
        private ICollection<StudentComment> CommentsGradedEffort { get; set; }
        private ICollection<StudentComment> CommentsGradedExam { get; set; }
        private ICollection<StudentComment> CommentsGradedFinal { get; set; }
        private ICollection<StudentComment> CommentsGradedTerm { get; set; }
        public virtual ICollection<APRequest> APRequests { get; set; }
        public virtual ICollection<Credit> TypedCredits { get; set; }
        public virtual ICollection<Credit> ValuedCredits { get; set; }
    }
}
