//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostMySQLConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.AttendanceMarkings = new HashSet<AttendanceMarking>();
            this.StudentComments = new HashSet<StudentComment>();
            this.Sections = new HashSet<Section>();
            this.StudentSignups = new HashSet<StudentSignup>();
            this.Dorms = new HashSet<Dorm>();
            this.WeekendsOnSundayStudyHall = new HashSet<Weekend>();
            this.SeatingChartSeats = new HashSet<SeatingChartSeat>();
            this.Permissions = new HashSet<Permission>();
            this.WeekendDisciplines = new HashSet<WeekendDiscipline>();
            this.LibraryPasses = new HashSet<LibraryPass>();
            this.CourseRequestComments = new HashSet<CourseRequestComment>();
            this.RegistrationRequests = new HashSet<RegistrationRequest>();
            this.StudentCalendarSpecialPermissions = new HashSet<StudentCalendarSpecialPermission>();
            this.Credits = new HashSet<Credit>();
            this.CourseRequests = new HashSet<CourseRequest>();
            this.Fingerprints = new HashSet<Fingerprint>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public bool isActive { get; set; }
        public int AdvisorID { get; set; }
        public int AcademicLevel { get; set; }
        public int GraduationYear { get; set; }
        public string BlackbaudId { get; set; }
        public string PreferredName { get; set; }
        public bool AllowPreferredNameInRecords { get; set; }
        public int SchoologyId { get; set; }
    
        public virtual ICollection<AttendanceMarking> AttendanceMarkings { get; set; }
        public virtual Faculty Advisor { get; set; }
        public virtual ICollection<StudentComment> StudentComments { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<StudentSignup> StudentSignups { get; set; }
        public virtual ICollection<Dorm> Dorms { get; set; }
        public virtual ICollection<Weekend> WeekendsOnSundayStudyHall { get; set; }
        public virtual ICollection<SeatingChartSeat> SeatingChartSeats { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<WeekendDiscipline> WeekendDisciplines { get; set; }
        public virtual ICollection<LibraryPass> LibraryPasses { get; set; }
        public virtual ICollection<CourseRequestComment> CourseRequestComments { get; set; }
        public virtual ICollection<RegistrationRequest> RegistrationRequests { get; set; }
        public virtual ICollection<StudentCalendarSpecialPermission> StudentCalendarSpecialPermissions { get; set; }
        public virtual ICollection<Credit> Credits { get; set; }
        public virtual ICollection<CourseRequest> CourseRequests { get; set; }
        public virtual ICollection<Fingerprint> Fingerprints { get; set; }
    }
}
