//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostMySQLConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeStampedSignature
    {
        public TimeStampedSignature()
        {
            this.LibrarySignedPasses = new HashSet<LibraryPass>();
            this.StudyHallSignedPasses = new HashSet<LibraryPass>();
        }
    
        public int id { get; set; }
        public int FacultyId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> AltTimeStamp { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        private ICollection<LibraryPass> LibrarySignedPasses { get; set; }
        public virtual ICollection<LibraryPass> StudyHallSignedPasses { get; set; }
    }
}
