//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostMySQLConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekendActivity
    {
        public WeekendActivity()
        {
            this.Adults = new HashSet<Faculty>();
            this.StudentSignups = new HashSet<StudentSignup>();
            this.Tags = new HashSet<ActivityCategory>();
        }
    
        public int id { get; set; }
        public int WeekendIndex { get; set; }
        public string Name { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public string Description { get; set; }
        public bool isSignup { get; set; }
        public bool isMandatory { get; set; }
        public bool showStudents { get; set; }
        public int MaxSignups { get; set; }
        public int Duration { get; set; }
        public bool IsOffCampus { get; set; }
        public bool IsDeleted { get; set; }
        public string GoogleCalendarEventId { get; set; }
    
        public virtual Weekend Weekend { get; set; }
        public virtual ICollection<Faculty> Adults { get; set; }
        public virtual ICollection<StudentSignup> StudentSignups { get; set; }
        public virtual ICollection<ActivityCategory> Tags { get; set; }
    }
}
