<%@ Page Title="" Language="C#" MasterPageFile="~/Default.Master" AutoEventWireup="true" CodeBehind="AttendanceView.aspx.cs" Inherits="WebhostV2.AttendanceView" %>
<%@ Register src="UserControls/AttendanceReview/StudentAttendanceTable.ascx" tagname="StudentAttendanceTable" tagprefix="uc1" %>
<%@ Register Src="~/UserControls/AttendanceReview/AttendanceTicker.ascx" TagPrefix="uc1" TagName="AttendanceTicker" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <meta http-equiv="refresh" content="300" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="header_cp" runat="server">
    Attendance Review
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="sidebar_cp" runat="server">
    <nav class="control">
        <header>Student</header>
        <ajaxToolkit:ComboBox ID="StudentSelector" runat="server" AutoCompleteMode="SuggestAppend"></ajaxToolkit:ComboBox>
        <asp:Button ID="LoadBtn" runat="server" Text="Load Attendance" OnClick="LoadBtn_Click" />
        <header>Dates</header>
        <asp:TextBox ID="StartDateInput" runat="server"></asp:TextBox>
        <ajaxToolkit:CalendarExtender ID="StartDateInput_CalendarExtender" runat="server" TargetControlID="StartDateInput">
        </ajaxToolkit:CalendarExtender>
        <asp:TextBox ID="EndDateInput" runat="server"></asp:TextBox>
        <ajaxToolkit:CalendarExtender ID="EndDateInput_CalendarExtender" runat="server" TargetControlID="EndDateInput">
        </ajaxToolkit:CalendarExtender>
        <asp:Button ID="SelectDatesBtn" runat="server" Text="SelectDates" OnClick="SelectDatesBtn_Click" />
        <asp:Button ID="GetAttendanceDump" runat="server" Text="Get Student Attendance Dump" ToolTip="Get all this student's attendance records for the selected dates." OnClick="GetAttendanceDump_Click"/>
    </nav>
    <nav class="control">
        <header>Detention Reports</header>
        <asp:Button ID="DetentionListBtn" runat="server" Text="Get Detention List" OnClick="DetentionListBtn_Click" ToolTip="Generate this week's Detention List based on the Data Entered in Webhost." />
        <br />
        <asp:Button ID="SendEmail" runat="server" OnClick="SendEmail_Click" Text="Send Detention Email" ToolTip="Send the autogenerated email to all students and their advisors with details of why they are on the detention list." />
        <br />
        <asp:Button ID="SummaryBtn" runat="server" OnClick="SummaryBtn_Click" Text="Get Attendance Summary" ToolTip="Get a Quick overall summary of student Attendances over the course of the entire school year by Lates, Cuts, and Excused." />
        <header>Engagement Reports</header>
        <asp:TextBox ID="MidTermDateInput" runat="server"></asp:TextBox>
        <ajaxToolkit:CalendarExtender ID="MidTermDateInput_CalendarExtender" runat="server" TargetControlID="MidTermDateInput">
        </ajaxToolkit:CalendarExtender>
        <asp:RadioButtonList ID="BeforeOrAfter" runat="server">
            <asp:ListItem Selected="True" Value="0">Pre Midterms</asp:ListItem>
            <asp:ListItem Value="1">Post Midterms</asp:ListItem>
        </asp:RadioButtonList>
        <asp:Button ID="GetHalfTermAttendance" runat="server" Text="Get Attendance Report for Engagement Levels" OnClick="GetHalfTermAttendance_Click" ToolTip="Generate the report of Student Attendance used to account into Engagement Grades." />
    </nav>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="main_cp" runat="server">

    <uc1:AttendanceTicker runat="server" id="AttendanceTicker1" />
    <article class="control">

        <uc1:StudentAttendanceTable ID="StudentAttendanceTable1" runat="server" />

    </article>
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="footer_cp" runat="server">
</asp:Content>
